### ISSUE TITLE
Missing model property path

### ISSUE THREAD

**Issue by todesignandconquer** [dustinspecker/deku-redux-connect#25]
Deku passes along a `path` property to its rendered component, but it is missing from the mapped props when using `connect()`: https://github.com/dustinspecker/deku-redux-connect/blob/master/src/index.js#L42

`path` property in Deku docs: http://anthonyshort.me/deku/docs/basics/components.html

> The unique path to the component within the entire component tree.
> 
> ```
> function render ({ path }) {
>   return <a onClick={updateState(path)}>Save</a>
> }
> ```

**Comment by dustinspecker** [comment]
Thanks for pointing this out! I'm going to be busy the next couple of days, but I'll try to get it fixed soon. Or I'm open to a PR if anyone wants to tackle it.

**Comment by dustinspecker** [comment]
Thanks again for reporting this. Sorry for the delay. The fix should be released after CI passes.

**Comment by todesignandconquer** [comment]
Thank you very much!
